Simplify check for needed status update

diff --git a/post-cdash-status b/post-cdash-status
--- a/post-cdash-status
+++ b/post-cdash-status
@@ -38,6 +38,13 @@ readonly status_response=$(
 
 readonly statuses=$(jq -r '[.[].context] | @json' <<< $status_response)
 
+if [ "true" != $(jq -re "all(. != \"${GITHUB_STATUS_NAME}\")" <<<"${statuses}") ]; then
+  echo "No status updates needed."
+  exit 0;
+fi
+
+echo "Need to post a status for context ${GITHUB_STATUS_NAME}"
+
 post_body="$(cat<<EOF
 {
   "state": "success",
@@ -50,22 +57,16 @@ EOF
 
 post_url="${API_BASE}/statuses/${COMMIT_SHA}"
 
-if [ "true" == $(jq -re "all(. != \"${GITHUB_STATUS_NAME}\")" <<<"${statuses}") ]; then
-  echo "Need to post a status for context ${GITHUB_STATUS_NAME}"
+readonly response=$(
+  curl -X POST -q -s \
+       -H "Authorization: Bearer ${GITHUB_TOKEN}" \
+       -H "Content-Type: application/json" \
+       -H "Accept: application/vnd.github+json" \
+       -H "X-GitHub-Api-Version: 2022-11-28" \
+       -d "${post_body}" "${post_url}")
 
-  readonly response=$(
-    curl -X POST -q -s \
-         -H "Authorization: Bearer ${GITHUB_TOKEN}" \
-         -H "Content-Type: application/json" \
-         -H "Accept: application/vnd.github+json" \
-         -H "X-GitHub-Api-Version: 2022-11-28" \
-         -d "${post_body}" "${post_url}")
-
-    if [ "false" == $(jq -r 'has("creator")') <<<"$response" ]; then
-      echo "Failed to create status for '${API_BASE}/commits/${COMMIT_SHA}'"
-      echo -e "Request returned:\n$response"
-      exit 3
-    fi
-else
-  echo "No status updates needed."
+if [ "false" == $(jq -r 'has("creator")') <<<"$response" ]; then
+  echo "Failed to create status for '${API_BASE}/commits/${COMMIT_SHA}'"
+  echo -e "Request returned:\n$response"
+  exit 3
 fi
